version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_socket_app
    restart: unless-stopped
    volumes:
      - .:/var/www
    networks:
      - laravel_network

  web:
    image: nginx:alpine
    container_name: nginx_socket_app
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - /root/laravel-socket-app/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /root/laravel-socket-app/nginx/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

